version: '1.0'
stages:
  - "clone"
  - "build"
steps:
  main_clone:
    title: "Cloning main repository..."
    stage: "clone"
    type: "git-clone"
    repo: "cedriclange/android-base"
    revision: "${{CF_BRANCH}}"
    git: "github"
  BuildIt:
    title: "Packaging Android App"
    stage: "build"
    type: "build"
    image: "nextcloudci/android:android-48"
    commands:
     - ./gradlew build  --no-daemon --gradle-user-home=/codefresh/volume/.gradle
